export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PENDING = "PENDING",
}

export interface User {
  id: string;
  tenant_id: string;
  name: string;
  email: string;
  mfa_enabled: boolean;
  // Roadmap (segurança): true na criação e sempre que o admin redefine a senha - bloqueia toda
  // rota autenticada (via requireAuth) exceto POST /api/auth/change-password até ser zerado.
  must_change_password: boolean;
  status: UserStatus;
  role_id: string;
  created_at: string;
  updated_at: string;
  last_login_at?: string;
  // F3 (01/09/2026): quando a senha atual foi definida. E o que a VALIDADE da politica de senha
  // mede (`precisaTrocarSenha`). Ausente em quem nunca trocou - e ausente conta como VENCIDA
  // quando ha validade configurada.
  password_changed_at?: string;
}

export interface Role {
  id: string;
  tenant_id: string;
  name: string;
  description: string;
  permissions: string[];
}

export interface TeamMembership {
  id: string;
  tenant_id: string;
  manager_id: string;
  engineer_id: string;
  created_at: string;
}

export type ProjectStatus = "draft" | "analysis_in_progress" | "waiting_customer" | "waiting_internal" | "completed" | "canceled";

export interface Project {
  id: string;
  name: string;
  customer_name: string;
  // CDC 16 (D31): quando o projeto nasceu de uma Demanda vinda do CMCRM, estes
  // dois campos são a REFERÊNCIA do cliente e da oportunidade lá. Ausentes num
  // projeto criado pelo intake, que continua funcionando sem CRM nenhum.
  crm_company_id?: string;
  crm_opportunity_id?: string;
  opportunity_name: string;
  vertical: string;
  description: string;
  status: ProjectStatus;
  deadline: string;
  proposal_validity_date: string;
  owner_user_id: string;
  output_language: "Portuguese" | "English" | "Spanish";
  proposal_language: "Portuguese" | "English" | "Spanish";
  ai_orientation_mode: "Vendor-neutral" | "Preferred manufacturer" | "Mandatory manufacturer" | "Existing customer standard" | "Free AI recommendation" | "Custom instruction";
  ai_orientation_text: string;
  selected_approval_workflow_id: string;
  procurement_modality?: string;
  procurement_subtype?: string;
  custom_modality?: string;
  created_at: string;
  updated_at: string;
}

// Add-on module (Fase 6) - only relevant for tenants with the "poc" module entitlement.
export type PocStatus = "not_started" | "planned" | "in_progress" | "blocked" | "completed";

export interface Poc {
  id: string;
  project_id?: string;
  standalone_customer_name?: string;
  standalone_contact_name?: string;
  standalone_contact_email?: string;
  standalone_contact_phone?: string;
  name: string;
  objective: string;
  status: PocStatus;
  archived: boolean;
  // Denormalized from PocAcceptance.decision by the list endpoint (GET /api/pocs) so the Kanban
  // board can color a completed card won/lost without an N+1 fetch per card.
  acceptance_decision?: "pending" | "won" | "lost";
  start_date: string;
  end_date: string;
  owner_user_id: string;
  owner_name?: string;
  customer_contact_name: string;
  customer_contact_role: string;
  address_zip?: string;
  address_street?: string;
  address_number?: string;
  address_complement?: string;
  address_neighborhood?: string;
  address_city?: string;
  address_state?: string;
  created_at: string;
  updated_at: string;
}

export interface PocSuccessCriterion {
  id: string;
  poc_id: string;
  description: string;
  done: boolean;
  order: number;
  created_at: string;
  updated_at: string;
}

export type PocEquipmentStatus = "shipped" | "at_customer" | "returned";

export interface PocEquipmentItem {
  id: string;
  poc_id: string;
  name: string;
  serial_number?: string;
  status: PocEquipmentStatus;
  manufacturer?: string;
  part_number?: string;
  source_bom_item_id?: string;
  kb_match_count: number;
  datasheet_knowledge_base_document_id?: string;
  shipping_invoice_original_filename?: string;
  return_invoice_original_filename?: string;
  tracking_code?: string;
  tracking_carrier_status?: string;
  tracking_last_checked_at?: string;
  created_at: string;
  updated_at: string;
}

// Trimmed view of a Project's BOMItem (src/types.ts's BOMItem, generated by document analysis)
// offered as an importable candidate for a POC's equipment list - only the fields actually
// useful here, not the full analysis-time metadata (source_reference, sourced_via_*, etc.).
export interface PocBomCandidate {
  bom_item_id: string;
  equipment_name: string;
  manufacturer: string;
  part_number: string;
  quantity: number;
  specification: string;
}

export type PocTaskStatus = "planned" | "in_progress" | "done";

export interface PocTask {
  id: string;
  poc_id: string;
  name: string;
  start_date: string;
  duration_days: number;
  status: PocTaskStatus;
  depends_on_task_id?: string;
  generated_by_ai: boolean;
  edited_manually: boolean;
  created_at: string;
  updated_at: string;
}

export type PocTestCaseStatus = "pending" | "in_progress" | "approved" | "failed";

export interface PocTestCase {
  id: string;
  poc_id: string;
  code: string;
  title: string;
  objective: string;
  steps: string;
  expected_result: string;
  status: PocTestCaseStatus;
  generated_by_ai: boolean;
  edited_manually: boolean;
  created_at: string;
  updated_at: string;
}

export type PocAcceptanceDecision = "pending" | "won" | "lost";

export interface PocAcceptance {
  id: string;
  poc_id: string;
  decision: PocAcceptanceDecision;
  signed_document_original_filename?: string;
  signed_by?: string;
  signed_at?: string;
  notes?: string;
  pending_approval: boolean;
  approved_by_user_id?: string;
  approved_at?: string;
  created_at: string;
  updated_at: string;
}

export interface PocFinalReportQuestion {
  id: string;
  poc_id: string;
  question: string;
  answer?: string;
  order: number;
  generated_by_ai: boolean;
  edited_manually: boolean;
  created_at: string;
  updated_at: string;
}

export interface Document {
  id: string;
  project_id: string;
  filename: string;
  original_filename: string;
  mime_type: string;
  file_size: number;
  storage_provider: "local" | "s3" | "gcs";
  storage_path: string;
  detected_document_type: string;
  manual_document_type?: string;
  ai_classification_confidence: number;
  version: number;
  language: string;
  uploaded_by: string;
  created_at: string;
}

export interface AIAnalysisJob {
  id: string;
  project_id: string;
  status: "idle" | "running" | "completed" | "failed";
  ai_provider: string;
  ai_model: string;
  prompt_template_version: string;
  started_at?: string;
  completed_at?: string;
  error_message?: string;
  token_input?: number;
  token_output?: number;
  estimated_cost?: number;
  created_by: string;
  correlation_id: string;
}

export interface CriticalRequirement {
  requirement_id: string;
  category: "technical" | "commercial" | "contractual" | "operational" | "security" | "integration" | "infrastructure" | "deadline" | "support" | "maintenance" | "documentation" | "training";
  description: string;
  source_document: string;
  source_page_or_section: string;
  source_snippet: string;
  priority: "high" | "medium" | "low";
  mandatory_or_optional: "mandatory" | "optional";
  compliance_status: "compliant" | "partially_compliant" | "non_compliant" | "not_enough_information";
  evidence_type: "directly_supported" | "inferred_from_documents" | "user_provided_instruction" | "assumption" | "missing_information" | "requires_customer_confirmation";
  confidence: number;
  notes: string;
}

export interface ProjectRisk {
  risk_id: string;
  title: string;
  description: string;
  severity: "low" | "medium" | "high" | "critical";
  probability: "low" | "medium" | "high";
  impact: string;
  source_document: string;
  source_page_or_section: string;
  source_snippet: string;
  mitigation: string;
  owner_area: string;
  requires_customer_clarification: boolean;
  evidence_type: string;
  confidence: number;
}

export interface ProjectOpportunity {
  opportunity_id: string;
  title: string;
  description: string;
  business_value: string;
  source_document: string;
  source_page_or_section: string;
  suggested_solution: string;
  sales_strategy: string;
  priority: "high" | "medium" | "low";
  evidence_type: string;
  confidence: number;
}

export interface BOMItem {
  item_id: string;
  sku: string;
  part_number: string;
  equipment_name: string;
  manufacturer: string;
  quantity: number;
  unit: string;
  category: string;
  specification: string;
  source_reference: string;
  // Confiança (0-1) auto-reportada pela IA no momento da extração (análise inicial ou reanálise
  // de seção) de que equipment_name/specification realmente captura o que o documento pede -
  // diferente de match_confidence abaixo, que é sobre achar um produto real depois. Usada pra
  // decidir se uma reanálise pode substituir este item (server/routes/analysis.ts,
  // reconcileBomWithExisting) e pra sinalizar "revisar" na tela quando baixa. Ausente em BOMs
  // salvos antes desse campo existir.
  confidence?: number;
  sourced_via_web_search?: boolean;
  // True when this item was instead resolved from an approved Knowledge Base entry (checked
  // before falling back to a live web search) - mutually exclusive with sourced_via_web_search.
  sourced_via_knowledge_base?: boolean;
  // Set the moment a user hand-edits sku/part_number/manufacturer - takes over from
  // sourced_via_web_search/sourced_via_knowledge_base in the UI badge, since "found by search"
  // stops being true/relevant once a person has actually verified/corrected the value themselves.
  edited_by?: string;
  // Deterministic-enough brand-policy compliance signal (see server/routes/analysis.ts's
  // computeBrandPolicyCrossCheck) - absent/null on BOMs saved before this existed, or on items
  // where no brand policy applies at all (e.g. a cabinet/enclosure the mandated camera brand
  // doesn't make - a legitimate non-match, never flagged as a violation).
  brand_policy_applicable?: boolean | null;
  brand_policy_compliant?: boolean | null;
  brand_policy_note?: string | null;
  brand_policy_confidence?: "high" | "medium" | "low" | null;
  // Confiança na correspondência do equipamento em si (fabricante/PN/SKU), auto-reportada pelo
  // mesmo prompt de enriquecimento - sem custo de IA adicional. Diferente de
  // brand_policy_confidence, que é só sobre um achado de violação de política de marca ser
  // confiável, não sobre se o match em si está certo. Ausente em itens não enriquecidos (BOM
  // salvo antes desse campo existir, ou item que já tinha part_number preenchido).
  match_confidence?: "high" | "medium" | "low" | null;
  // Corroboração estatística determinística (computeEquipmentMatchCrossCheck) - true quando o
  // fabricante deste item destoa da maioria dos itens da mesma categoria neste BOM.
  manufacturer_outlier?: boolean;
}

export interface DynamicMatrixColumn {
  key: string;
  label: string;
}

// One point-to-point technical matrix per discipline the AI found in the source document (CFTV,
// Rede, Controle de Acesso, Elétrica...) - both which disciplines exist and which columns each
// one needs are decided per-analysis, not fixed platform-wide, so rows are a flexible key/value
// object keyed by that table's own `columns`.
export interface DynamicMatrix {
  discipline: string;
  columns: DynamicMatrixColumn[];
  rows: Record<string, string | number | boolean | null>[];
}

export interface PreliminarySchedulePhase {
  phase_id: string;
  phase_name: string;
  activities: string[];
  estimated_duration: string;
  dependencies: string[];
  responsible_area: string;
  assumptions: string;
  risks: string;
}

export interface ClarificationQuestion {
  question_id: string;
  question: string;
  reason: string;
  source_reference: string;
  related_requirement_or_risk: string;
  priority: "high" | "medium" | "low";
  target_audience: string;
}

export interface ExecutiveSummary {
  project_overview: string;
  customer_context: string;
  main_requirements: string;
  main_risks: string;
  main_opportunities: string;
  recommended_strategy: string;
  assumptions: string;
  next_steps: string;
}

export interface PricingRow {
  item_id: string;
  product_or_service: string;
  specification: string;
  quantity: number;
  unit: string;
  unit_price: number;
  total_price: number;
  currency: string;
  is_optional: boolean;
  discount: number;
}

export interface AnalysisResult {
  id: string;
  project_id: string;
  job_id: string;
  executive_summary: ExecutiveSummary;
  critical_requirements: CriticalRequirement[];
  risks: ProjectRisk[];
  opportunities: ProjectOpportunity[];
  bom: BOMItem[];
  point_to_point_table: DynamicMatrix[];
  preliminary_schedule: PreliminarySchedulePhase[];
  clarification_questions: ClarificationQuestion[];
  technical_proposal_draft: string;
  commercial_proposal_draft: string;
  review_status: "pending" | "reviewed" | "approved";
  approved_by?: string;
  approved_at?: string;
  created_at: string;
  updated_at: string;
  // Staleness signal for hardcoded logic (see src/aiLogicVersions.ts) - null on rows written
  // before this existed ("legacy/unknown", distinct from both stale and up-to-date).
  logic_versions?: Record<string, number> | null;
  // Computed server-side on GET /projects/:id/analysis-result (never sent by the client) -
  // true/false once logic_versions has that key, null when unknown/legacy.
  is_document_analysis_stale?: boolean | null;
  is_bom_enrichment_stale?: boolean | null;
}

export interface ConversationMessage {
  id: string;
  project_id: string;
  user_id: string;
  role: "user" | "model";
  message: string;
  ai_provider: string;
  ai_model: string;
  prompt_template_version: string;
  input_summary: string;
  output_summary: string;
  token_input: number;
  token_output: number;
  created_at: string;
}

export interface AuditLog {
  id: string;
  user_id: string;
  action: string;
  entity_type: string;
  entity_id: string;
  project_id?: string;
  ip_address: string;
  user_agent: string;
  metadata: string; // JSON string
  created_at: string;
}

export interface DebugLog {
  id: string;
  timestamp: string;
  log_level: "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR" | "FATAL";
  service_name: string;
  module_name: string;
  environment: string;
  correlation_id: string;
  request_id: string;
  // Explicit, caller-supplied tenant id (from the request's x-tenant-id header) - preferred over
  // the AsyncLocalStorage-based fallback in dbStore.addDebugLog, which is frequently absent by the
  // time a catch block or the central error handler runs (documented elsewhere in this codebase as
  // "AsyncLocalStorage context isn't reliably reaching route handlers").
  tenant_id?: string;
  user_id?: string;
  project_id?: string;
  document_id?: string;
  analysis_job_id?: string;
  proposal_id?: string;
  operation: string;
  message: string;
  status: string;
  duration_ms: number;
  error_code?: string;
  error_message?: string;
  safe_metadata: string; // JSON string
}

// Cached mirror of the ia_kb add-on's billing state, refreshed on every Fleet Manager heartbeat -
// never carries real provider cost, only the value already marked up (see fleetLicense.ts).
export interface IaKbBillingSnapshot {
  markup_percent: number;
  cycle_start: string | null;
  cycle_billed_cost_usd: number;
  cycle_call_count: number;
  next_due_date: string | null;
  last_synced_at: string;
}

// Per-task provider/model synced from the Fleet Manager once ia_kb is enabled - see
// server/utils/fleetLicense.ts and src/aiOrchestrator.ts's resolveProvider().
export interface IaKbTaskConfig {
  task_type: string;
  provider: string;
  model: string;
}

export interface PlatformSettings {
  id: string;
  ai_provider: string;
  default_model: string;
  document_analysis_model: string;
  proposal_generation_model: string;
  ai_api_key_encrypted?: string;
  ai_api_key_configured?: boolean;
  ai_api_key_masked?: string;
  openai_api_key_encrypted?: string;
  openai_api_key_configured?: boolean;
  openai_api_key_masked?: string;
  anthropic_api_key_encrypted?: string;
  anthropic_api_key_configured?: boolean;
  anthropic_api_key_masked?: string;
  // Phase 5 (AI orchestrator): intended provider per task type - see src/aiOrchestrator.ts.
  document_analysis_provider: string;
  critical_extraction_model: string;
  critical_extraction_provider: string;
  web_grounding_model: string;
  web_grounding_provider: string;
  proposal_generation_provider: string;
  spec_copilot_model: string;
  spec_copilot_provider: string;
  document_classification_model: string;
  document_classification_provider: string;
  poc_test_generation_model: string;
  poc_test_generation_provider: string;
  poc_schedule_generation_model: string;
  poc_schedule_generation_provider: string;
  poc_final_report_generation_model: string;
  poc_final_report_generation_provider: string;
  proposal_opinion_panel_model: string;
  proposal_opinion_panel_provider: string;
  pricing_budget_optimization_model: string;
  pricing_budget_optimization_provider: string;
  pricing_catalog_extraction_model: string;
  pricing_catalog_extraction_provider: string;
  // F6 (rodada 09/2026): slot proprio da reescrita de secao - ver o comentario da coluna em
  // prisma/schema.prisma para por que ela nao reusa proposal_generation.
  proposal_section_rewrite_model: string;
  proposal_section_rewrite_provider: string;
  // F7 (rodada 09/2026): sanacao por apontamento, gramatica por correcao pontual e coerencia de
  // TEXTO entre secoes. A coerencia NUMERICA continua deterministica (server/utils/proposalQa.ts)
  // e nao tem slot de IA nenhum, de proposito.
  proposal_finding_remediation_model: string;
  proposal_finding_remediation_provider: string;
  proposal_grammar_check_model: string;
  proposal_grammar_check_provider: string;
  proposal_section_coherence_model: string;
  proposal_section_coherence_provider: string;
  monthly_cost_cap_usd?: number | null;
  // Phase 7 (fleet/license management): this tenant's registration with the vendor's fleet
  // manager (a separate server). See src/fleetLicense.ts.
  fleet_manager_url?: string | null;
  fleet_manager_api_key_encrypted?: string;
  fleet_manager_enabled: boolean;
  storage_mode: "local" | "s3" | "gcs";
  local_storage_path: string;
  s3_bucket: string;
  s3_region?: string;
  s3_access_key_id?: string;
  s3_secret_access_key_encrypted?: string;
  s3_secret_access_key_configured?: boolean;
  s3_secret_access_key_masked?: string;
  gcs_bucket: string;
  gcs_project_id?: string;
  gcs_service_account_key_encrypted?: string;
  gcs_service_account_key_configured?: boolean;
  default_language: "Portuguese" | "English" | "Spanish";
  default_log_level: "DEBUG" | "INFO" | "WARN" | "ERROR";
  created_at: string;
  updated_at: string;
}

export interface PromptTemplate {
  id: string;
  name: string;
  type: string;
  content: string;
  factory_default: string;
  language: "Portuguese" | "English" | "Spanish";
  version: string;
  is_active: boolean;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface ProposalTemplate {
  id: string;
  name: string;
  description: string;
  template_type: "technical" | "commercial" | "technical_commercial" | "executive_summary" | "risk_report" | "bom_report" | "questions_report";
  language: "Portuguese" | "English" | "Spanish";
  file_type: "docx" | "doc" | "pdf";
  file_path: string;
  storage_provider: "local" | "s3" | "gcs";
  variables_schema: string;
  version: string;
  active: boolean;
  default_template: boolean;
  uploaded_by: string;
  created_at: string;
  updated_at: string;
}

export interface Proposal {
  // Item 18 do catalogo Reforma CloudMountain: o que o CLIENTE respondeu depois da liberacao.
  //
  // Quem decide ganho/perda e o CRM (`opportunities.status` no CMCRM). Estes campos cobrem o
  // cenario SEM integracao, em que o Comercial registra aqui a resposta e este produto empurra o
  // evento correspondente para a timeline do outro lado.
  client_decision?: "accepted" | "declined" | null;
  client_decision_at?: string | null;
  client_decision_by_user_id?: string | null;
  client_decision_note?: string | null;
  id: string;
  project_id: string;
  proposal_type: "technical" | "commercial" | "technical_commercial" | "executive_summary" | "risk_report" | "bom_report" | "questions_report";
  template_id: string;
  template_version: string;
  status: "draft" | "submitted" | "approved" | "rejected" | "released";
  language: "Portuguese" | "English" | "Spanish";
  docx_file_path: string;
  pdf_file_path: string;
  storage_provider: "local" | "s3" | "gcs";
  generated_by: string;
  generated_at: string;
  version: number;
  // PreSales F8 (versionamento por reabertura pós-rejeição) - ver o model Proposal em
  // prisma/schema.prisma. `proposal_group_id` é estável por cadeia (v1/v2/v3 compartilham o mesmo);
  // `previous_version_id` é o elo para trás, presente só a partir da v2.
  proposal_group_id: string;
  previous_version_id?: string | null;
  approval_workflow_id: string;
  // F6: nome-da-variavel-do-template -> texto aprovado por uma pessoa. Ver o comentario do campo
  // templateFieldValues em prisma/schema.prisma.
  template_field_values?: Record<string, string> | null;
  manual_pricing_table?: PricingRow[];
  payment_terms?: string;
  delivery_terms?: string;
  proposal_validity?: string;
  commercial_assumptions?: string;
  exclusions?: string;
  editable_content?: string;
  // Points at the most recent ProposalOpinionRun for this proposal - see
  // server/routes/proposals.ts's opinion-panel endpoints. Nullable: most proposals never have one.
  latest_opinion_run_id?: string | null;
}

// Roadmap item (customer_request): "Alerta de Risco de SLA via Base de Conhecimento" - flags a
// proposed commercial/SLA term against the approved Knowledge Base's own recorded lessons learned
// (by vertical/client), before the proposal is sent. Never invented risks: grounded in a specific
// KB entry (related_lesson), same discipline as the BOM enrichment's known_knowledge matching.
export interface SlaRiskFlag {
  term_excerpt: string;
  risk_description: string;
  related_lesson: string;
  severity: "high" | "medium" | "low";
}

export interface ApprovalWorkflow {
  id: string;
  name: string;
  description: string;
  active: boolean;
  applies_to: string; // e.g. "all", "high_risk", "commercial"
  stages: ApprovalStage[];
  created_at: string;
  updated_at: string;
}

export interface ApprovalStage {
  id: string;
  workflow_id: string;
  name: string;
  order: number;
  approver_type: "user" | "role";
  approver_user_id?: string;
  approver_role_id?: string;
  mandatory: boolean;
  conditions: string;
  created_at: string;
  updated_at: string;
}

export interface ApprovalDecision {
  id: string;
  proposal_id: string;
  stage_id: string;
  approver_user_id: string;
  decision: "approved" | "rejected";
  comments: string;
  created_at: string;
}

export interface IntegrationConnector {
  id: string;
  name: string;
  type: string; // e.g., "CRM", "ERP", "Notification", etc.
  status: "connected" | "disconnected" | "error";
  configuration: string; // JSON configuration
  // Derived by the API from `configuration` for display/editing convenience - not stored as-is.
  url?: string;
  sync_frequency?: string;
  // Masked (never raw) once a credential is configured.
  token?: string;
  api_key?: string;
  webhook_secret?: string;
  last_sync_status: string;
  last_sync_date?: string;
  error_message?: string;
  created_at: string;
  updated_at: string;
}

export type KnowledgeBaseEntryCategory = "bom_part_number" | "engineering_note" | "compliance_status" | "datasheet";
export type KnowledgeBaseEntryStatus = "pending" | "approved" | "rejected";
export type KnowledgeBaseEntrySource = "reactive_edit" | "uploaded_document" | "fleet_manager_global";

export interface KnowledgeBaseEntry {
  id: string;
  category: KnowledgeBaseEntryCategory;
  trigger: string;
  knowledge: string;
  status: KnowledgeBaseEntryStatus;
  source: KnowledgeBaseEntrySource;
  source_project_id?: string;
  source_project_name?: string;
  source_document_id?: string;
  source_document_name?: string;
  created_by: string;
  reviewed_by?: string;
  created_at: string;
  reviewed_at?: string;
  // Set only when source = "fleet_manager_global": the id of the entry on the Fleet Manager side
  // this was delivered from.
  fleet_global_entry_id?: string;
  // Set only for locally-created entries once uploaded to the Fleet Manager on a heartbeat.
  synced_to_fleet_at?: string;
}

export interface KnowledgeBaseDocument {
  id: string;
  filename: string;
  original_filename: string;
  mime_type: string;
  file_size: number;
  storage_provider: string;
  storage_path: string;
  uploaded_by: string;
  analyzed_at?: string;
  content_hash?: string;
  created_at: string;
}

// CDC 16 (integração CMCRM ↔ PreSales), Fase 1: a Demanda de pré-vendas.
//
// Não é um Project (D14): entra na fila SEM DONO e só vira Project quando
// alguém assume. O cliente aqui é REFERÊNCIA do CRM (D31) e nenhum contato
// pessoal viaja (D32) - por isso não há campo de pessoa nesta interface.
export interface DemandDocumentSummary {
  id: string;
  document_ref: string;
  filename: string;
  mime_type: string;
  size_bytes: number;
  sha256: string;
  has_content: boolean;
  has_extracted_text: boolean;
  content_received_at?: string | null;
  document_id?: string | null;
}

export interface Demand {
  id: string;
  demand_ref: string;
  sequence?: number | null;
  status: "queued" | "assigned" | "in_analysis" | "returned" | "cancelled" | "completed";
  company: {
    crm_company_id: string;
    name: string;
    legal_name?: string | null;
    tax_id?: string | null;
    cnpj_root?: string | null;
    sector?: string | null;
    segment?: string | null;
    type?: string | null;
  };
  opportunity: {
    crm_opportunity_id: string;
    name: string;
    deal_type?: string | null;
    stage?: string | null;
    value?: number | null;
    currency?: string;
    probability?: number | null;
    margin_percent?: number | null;
    expected_close_date?: string | null;
    risks?: string[];
    origin?: string | null;
  };
  title: string;
  vertical: string;
  description: string;
  objective?: string | null;
  deadline: string;
  proposal_validity_date: string;
  output_language: string;
  proposal_language: string;
  ai_orientation_mode: string;
  ai_orientation_text: string;
  procurement_modality?: string | null;
  procurement_subtype?: string | null;
  sent_by: { crm_user_id: string; name: string; email?: string | null };
  sent_at: string;
  /** Par que cruza ambientes (D03) - marcado visivelmente na fila. */
  cross_environment: boolean;
  crm_installation_id: string;
  queued_at: string;
  assigned_at?: string | null;
  analysis_started_at?: string | null;
  returned_at?: string | null;
  completed_at?: string | null;
  assigned_user_id?: string | null;
  assigned_to?: string | null;
  returned_reason?: string | null;
  project_id?: string | null;
  documents: DemandDocumentSummary[];

  // ── CDC 16 Fase 5 ─────────────────────────────────────────────────────────
  /** Prazo da etapa ainda devida (D19). Nulo sem SLA, e nulo em estado terminal. */
  due_at?: string | null;
  sla_stage?: "assume" | "analysis" | "proposal" | null;
  sla_stage_label?: string | null;
  /** "manager" (direcionada), "auto" (menor carga, D40) ou nulo (auto-serviço). */
  assignment_source?: "manager" | "auto" | null;
  assigned_by?: string | null;
  return_requested_at?: string | null;
  return_requested_by?: string | null;
  return_request_reason?: string | null;
  return_decided_at?: string | null;
  return_rejection_reason?: string | null;

  // ── CDC 16 Fase 7 ─────────────────────────────────────────────────────────
  /** Pedido de cancelamento vindo do CRM, já aprovado pelo líder direto (D18). */
  cancellation_requested_at?: string | null;
  cancellation_justification?: string | null;
  cancellation_approved_by?: string | null;
  cancellation_closed_at?: string | null;
  cancellation_closed_by?: string | null;
  /** Como o pedido terminou: `cancelled` (encerrada) ou `completed` (concluída mesmo assim). */
  cancellation_outcome?: "cancelled" | "completed" | null;
  /** Atualizações pós-envio aguardando decisão (D27). No detalhe vêm todas. */
  pending_updates?: DemandUpdateSummary[];
}

/** Uma atualização pós-envio, com o antes e o depois campo a campo (D27). */
export interface DemandUpdateSummary {
  id: string;
  /** `oportunidade_perdida` (D29), `prazo`, `escopo`, `comercial` ou `documentos`. */
  kind: string;
  note?: string | null;
  changed_at: string;
  received_at: string;
  changed_by?: string | null;
  changes: Array<{ campo: string; rotulo: string; antes: string | null; depois: string | null }>;
}

/** Uma execução do expurgo em cascata (D35), como a tela a lê. */
export interface CrmPurgeExecutionSummary {
  id: string;
  reason: "retention" | "data_subject_request";
  crm_installation_id: string;
  targets: Array<{ kind: string; crm_id: string }>;
  results: Array<{
    kind: string;
    crm_id: string;
    deleted: number;
    documents: Array<{ document_ref: string; sha256: string; file_deleted: boolean; materialized: boolean }>;
    demands: string[];
    projects_unlinked: number;
    error?: string;
  }>;
  documents_deleted: number;
  demands_deleted: number;
  files_deleted: number;
  projects_unlinked: number;
  executed_at: string;
}

/** CDC 16 F5: a configuração de prazo e de atribuição da instalação (D16, D19). */
export interface DemandSlaSettings {
  /** Falso enquanto ninguém configurou nada - o estado de toda instalação hoje. */
  configured: boolean;
  enabled: boolean;
  assume_hours: number;
  analysis_hours: number;
  proposal_hours: number;
  assignment_policy: "auto_servico" | "direcionamento" | "automatico";
  managers: Array<{ id: string; name: string }>;
  manager_permission: string;
}

/** CDC 16 F5: um prazo que venceu (D19). */
export interface DemandSlaAlert {
  id: string;
  demand_id: string;
  demand_ref: string;
  title: string;
  company_name: string;
  demand_status: string;
  assigned_to: string | null;
  stage: "assume" | "analysis" | "proposal";
  stage_label: string;
  due_at: string;
  detected_at: string;
  recipient_kind: "manager" | "team";
  recipient_user_ids: string[];
  acknowledged_at: string | null;
}

/** CDC 16 F5: a medição de tempo de resposta (D20). Por pessoa, só aqui. */
export interface DemandMeasurement {
  amostraAteAssumir: number;
  amostraAteAnalise: number;
  amostraAteConcluir: number;
  mediaAteAssumirSegundos: number | null;
  mediaAteAnaliseSegundos: number | null;
  mediaAteConcluirSegundos: number | null;
  devolvidas: number;
  total: number;
}

export interface DemandPerformance {
  days: number;
  since: string;
  // F9: qual das duas leituras a rota devolveu (resposta F do dono na F8).
  // "team" = o gerente, e `people` traz o time inteiro; "self" = qualquer outra
  // pessoa com `demand:read`, e `people` traz só a linha dela. A tela precisa
  // do campo para rotular: sem ele, "uma pessoa em people" seria
  // indistinguível de "o time tem uma pessoa só".
  scope?: "team" | "self";
  team: DemandMeasurement;
  people: Array<{ user_id: string; name: string } & DemandMeasurement>;
}

/**
 * F9: a resposta paginada de `GET /api/demands`.
 *
 * A rota devolvia um array puro até a F8. Passou a devolver envelope porque
 * "5 por vez e pagina as antigas" precisa do TOTAL do recorte — sem ele a tela
 * não sabe se há próxima página —, e porque a ordem e o recorte escolhidos
 * voltam ecoados: a tela desenha o cabeçalho a partir do que o servidor de fato
 * aplicou, e não a partir do que ela pediu.
 */
export interface DemandPage {
  items: Demand[];
  total: number;
  limit: number;
  offset: number;
  sort: string;
  dir: "asc" | "desc";
  verticals: Array<{ vertical: string; count: number }>;
  /**
   * F10: os contadores dos avisos, calculados sobre o RECORTE INTEIRO e nunca
   * sobre a página. É o que destrava a página de cinco linhas: até a F9 a tela
   * contava os avisos sobre as linhas carregadas e por isso pedia a fila toda
   * (`limit=200`), porque com uma página curta eles passariam a subcontar — e
   * aviso que subconta é pior do que aviso nenhum, porque parece resolvido.
   *
   * Dois deles são recortados por QUEM PERGUNTA (atualização pendente e
   * cancelamento aberto são trabalho de quem assumiu); o terceiro, a devolução
   * esperando decisão, é do gerente e vale para o recorte inteiro.
   */
  counts?: {
    return_pending: number;
    my_pending_updates: number;
    my_cancellations: number;
  };
}

export interface DemandQueueSummary {
  total: number;
  queued: number;
  assigned: number;
  in_analysis: number;
  returned: number;
  cancelled: number;
  completed: number;
}
